FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye 
# Use any image suitable for your project

WORKDIR /home/vscode/workspace

# opencode
RUN sudo apt update && sudo apt install nodejs npm -y
RUN npm i -g opencode-ai
